### ISSUE TITLE
Fee appear as ETH instead of RBTC

### ISSUE THREAD

**Issue by bitcoinuser** [liquality/wallet#32]
Fee appear as ETH instead of RBTC

![Captura de tela de 2021-01-10 00-04-59](https://user-images.githubusercontent.com/1178856/104113367-df232200-52d7-11eb-8888-5b81e99d1e10.png)

Liquality 0.11

**Comment by bradleySuira** [comment]
Fixed now in the 0.13.0 version

**Comment by bitcoinuser** [comment]
Hi @bradleySuira here is still wrong. The fee is not 0.06 RBTC is 0.06 gwei.

![Captura de tela de 2021-01-20 16-19-49](https://user-images.githubusercontent.com/1178856/105224294-c1f21d00-5b3b-11eb-9eb0-eaa6b5ca381f.png)

**Comment by bitcoinuser** [comment]
Another thing:

Near this info, should appear the value in Dollar too. Thanks.
